motor_pins:
  left_motor: [17, 18, 22]   # IN1, IN2, EN
  right_motor: [23, 24, 25]  # IN3, IN4, EN

camera:
  resolution: [640, 480]
  frame_rate: 30

lidar:
  min_range: 0.1
  max_range: 12.0

imu:
  update_rate_hz: 50

rf_comm:
  frequency_mhz: 433
  baud_rate: 9600

navigation:
  obstacle_threshold_m: 0.5
  default_speed: 0.3
